/**
 * AUTO-GENERATED by prebuild — DO NOT EDIT.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */

export { default as Badge } from '@/components/ui/badge/Badge.vue'
export type * from '@/components/ui/badge/Badge.vue'
export * from '@/components/ui/badge/badge-variants'
