/**
 * AUTO-GENERATED by prebuild — DO NOT EDIT.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */

export { default as Button } from '@/components/ui/button/Button.vue'
export type * from '@/components/ui/button/Button.vue'
export * from '@/components/ui/button/button-variants'
export * from '@/components/ui/button/shared-button-variants'
