/**
 * AUTO-GENERATED by prebuild — DO NOT EDIT.
 * To add public exports, edit the underlying .vue/.ts file (it will be
 * picked up automatically on the next prebuild).
 */

export { default as Textarea } from '@/components/ui/textarea/Textarea.vue'
export type * from '@/components/ui/textarea/Textarea.vue'
export * from '@/components/ui/textarea/textarea-variants'
